# Generated by Django 3.1.2 on 2020-10-27 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('text', models.TextField(blank=True, max_length=300, verbose_name='text')),
                ('count', models.PositiveIntegerField(default=0)),
                ('img', models.CharField(blank=True, max_length=100, verbose_name='img')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='price')),
                ('tag', models.CharField(default='', max_length=100, unique=True, verbose_name='tag')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='username')),
                ('password', models.TextField(verbose_name='password')),
                ('district', models.PositiveIntegerField(default=None, null=True, verbose_name='district')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('phone', models.CharField(max_length=12, verbose_name='phone')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('district', models.PositiveIntegerField(default=0, verbose_name='district')),
                ('status', models.IntegerField(
                    choices=[(-1, 'order canceled'), (0, 'processing'), (1, 'took order'), (2, 'delivering'),
                             (3, 'finish'), (4, 'lose')], default=0, verbose_name='status')),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.user')),
            ],
        ),
    ]
