# Generated by Django 3.1.2 on 2020-10-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201023_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(blank=True, max_length=100, unique=True, verbose_name='title')),
                ('text', models.TextField(blank=True, max_length=300, verbose_name='text')),
                ('count', models.IntegerField(default=0)),
                ('img', models.CharField(blank=True, max_length=100, unique=True, verbose_name='img')),
            ],
        ),
    ]
