# Generated by Django 3.1.2 on 2020-10-25 17:48

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0005_merge_20201025_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='username')),
                ('password', models.TextField(default=main.models.pass_gen, verbose_name='password')),
                ('district', models.IntegerField(default=0, verbose_name='district')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='username')),
                ('password', models.TextField(default=main.models.pass_gen, verbose_name='password')),
                ('invitation_code', models.TextField(default=main.models.pass_gen, verbose_name='invitation_code')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('phone', models.IntegerField(verbose_name='phone')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('district', models.IntegerField(default=0, verbose_name='district')),
                ('status', models.IntegerField(
                    choices=[(-1, 'order canceled'), (1, 'took order'), (2, 'delivering'), (3, 'finish'), (4, 'lose')],
                    verbose_name='status')),
                ('courier', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT,
                                              to='main.courier')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
