# Generated by Django 3.1.2 on 2020-10-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0006_auto_20201025_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='phone'),
        ),
    ]
